### ISSUE TITLE
Abstract?

### ISSUE THREAD

**Issue by Kreyren** [Kron4ek/wine_scripts#6]
What is a purpose of this project? Why is winetricks not sufficient?

winetricks is able to configure wineprefix with requested game assuming compatiblity provided and fetching wine shoudn't be hard to implement since wine provides binary packages on https://dl.winehq.org/wine/source/ and check to determine which while to use [system/binary] shoudn't be hard :thinking: 

Referencing https://github.com/PhoenicisOrg/phoenicis/issues/1996 since it was discussed there.

**Comment by Kron4ek** [comment]
It's for my own purposes primarily as i share games on some site.

**Comment by Kreyren** [comment]
@Kron4ek What is the purpose then?

**Comment by Kron4ek** [comment]
This project is for creating portable Windows apps with bundled Wine and with ability to recreate prefix from the scratch. Actually it's a lot simpler to use preconfigured Wine prefixes, but recreating prefixes from the scratch is more neat solution.

Configuring prefix by installing things like xact or d3dx9 (for example using winetirkcs) is not the only thing that required. Sometimes it's also necessary to import reg files to registry, copy preconfigured application settings or execute some scripts before launching application, and this project can do all these things.

**Comment by Kreyren** [comment]
> Actually it's a lot simpler to use preconfigured Wine prefixes, but recreating prefixes from the scratch is more neat solution.

The issue with that is terms of service for specific wineapps since they prevent redistribution -> if you provide wineprefix with league of legends for example you are breaking this agreenment. So +1 to that

> Sometimes it's also necessary to import reg files to registry, run some installers, copy preconfigured application settings or execute some scripts before launching application, and this project can do all these things.

Winetricks can also do that.. Just try `winetricks games list`

**Comment by Kron4ek** [comment]
>  Winetricks can do all of that.. Just try winetricks games list

The problem is there is a very limited amount of games there.

**Comment by Kreyren** [comment]
@Kron4ek Why is it saner to make separate project that doesn't introduce anything new when you can contribute to winetricks with these then?

**Comment by Kron4ek** [comment]
Besides few amount of available games, winetricks is not as flexible and convenient for me, and i don't want do learn internal winetricks syntax to make a contribution. 

> Why is it saner to make separate project that doesn't introduce anything new when you can contribute to winetricks with these then?

Well, it's not about sanity, it's about my wishes. Yes, this project is publicly available but that doesn't mean that it should be useful for everyone or that it should introduce something new, it's enough that it's useful for me (as i said earlier it's for my own purpuses). It doesn't harm anything in any way and i don't make anyone to use it after all.

**Comment by Kreyren** [comment]
meh
